<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__ . "/src")
    ->exclude([
        'autogenerated_content',
        'tests',
    ]);

return (new PhpCsFixer\Config())
    ->setRules([
        '@Symfony'                    => true,
        '@PHP82Migration'             => true,
        'class_attributes_separation' => [
            'elements' => [
                'const'        => 'none',
                'method'       => 'one',
                'property'     => 'one',
                'trait_import' => 'none',
                'case'         => 'none',
            ],
        ],
        'binary_operator_spaces'      => [
            'operators' => [
                '='  => 'align_single_space',
                '=>' => 'align_single_space',
            ],
        ],
        'concat_space'                => [
            'spacing' => 'one',
        ],
        'global_namespace_import'     => [
            'import_classes' => true,
        ],
        // @deprecated option. Find another solution: https://cs.symfony.com/doc/rules/basic/braces.html
        //        'braces' => [
        //            'position_after_functions_and_oop_constructs' => 'same',
        //        ],
    ])
    ->setFinder($finder);
