<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Finder;
use PhpCsFixer\Runner\Parallel\ParallelConfigFactory;

$finder = new Finder()
    ->in([
        __DIR__ . "/src",
        __DIR__ . "/tests",
    ])
    ->ignoreVCSIgnored(true)
    ->notName('bundles.php')
    ->exclude([
        'autogenerated_content',
        'tests/phpstan',
    ]);

return new Config()
    ->setParallelConfig(ParallelConfigFactory::detect())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony'                    => true,
        '@Symfony:risky'              => true,
        '@PHP8x4Migration'            => true,
        'ordered_imports'             => true,
        'class_attributes_separation' => [
            'elements' => [
                'const'        => 'none',
                'method'       => 'one',
                'property'     => 'one',
                'trait_import' => 'none',
                'case'         => 'none',
            ],
        ],
        'binary_operator_spaces'      => [
            'operators' => [
                '='  => 'align_single_space',
                '=>' => 'align_single_space',
            ],
        ],
        'concat_space'                => [
            'spacing' => 'one',
        ],
        'global_namespace_import'     => [
            'import_classes' => true,
        ],
        'trailing_comma_in_multiline' => [
            'elements' => [
                'arrays',
                'arguments',
                'parameters',
            ],
        ],
        // @deprecated option. Find another solution: https://cs.symfony.com/doc/rules/basic/braces.html
        //        'braces' => [
        //            'position_after_functions_and_oop_constructs' => 'same',
        //        ],
    ])
    ->setFinder($finder);
